[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "A Cheat Mod using UnityModMenuAPI."
websiteUrl = "https://github.com/Hamunii/UnityModMenuAPI"
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Hamunii-UnityModMenuAPI = "1.0.0"

[build]
icon = "./icon.png"
readme = "./LC_README.md"
outdir = "./Packages"

[[build.copy]]
source = "./LC_CHANGELOG.md"
target = "/CHANGELOG.md"

[[build.copy]]
source = "../bin/Release/netstandard2.1/Hamunii.UnityModMenuAPI.CoreMod.LC.dll"
target = "/BepInEx/plugins/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "libraries", ]