[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "A Mod Menu API for Unity Mono games."
websiteUrl = "https://github.com/Hamunii/ModMenuAPI"
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "../../README.md"
outdir = "./Packages"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/Hamunii.ModMenuAPI.dll"
target = "/BepInEx/plugins/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "libraries", ]