name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET Env
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.203"

      - name: Restore Solution
        run: |
          dotnet restore ModMenuAPI
          dotnet tool restore --tool-manifest ./ModMenuAPI/.config/dotnet-tools.json

      - name: Pack Solution
        run: |
          dotnet pack ModMenuAPI --configuration Release

      - name: Upload Thunderstore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: ./ModMenuAPI/Thunderstore/Packages/*.zip

      - name: Upload NuPkg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg-build
          path: ./ModMenuAPI/bin/Release/*.nupkg
