name: Release

on:
  release:
    types: [released, prereleased]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET Env
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.203"

      - name: Restore Solution
        run: |
          dotnet restore ModMenuAPI
          dotnet tool restore --tool-manifest ./ModMenuAPI/.config/dotnet-tools.json

      - name: Pack Solution
        run: |
          dotnet pack ModMenuAPI --configuration Release

      - name: Upload Thunderstore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: ./ModMenuAPI/Thunderstore/Packages/*.zip

      - name: Upload NuPkg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg-build
          path: ./ModMenuAPI/bin/Release/*.nupkg

  upload-release-artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Thunderstore Artifact
        uses: actions/download-artifact@v4
        with:
          name: thunderstore-build
          path: ./ModMenuAPI/Thunderstore/Packages/

      - name: Upload artifacts to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./ModMenuAPI/Thunderstore/Packages/*.zip

  deploy-nuget:
    name: Deploy to NuGet
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Download nupkg artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg-build
          path: ./ModMenuAPI/bin/Release

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.203"

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push ./ModMenuAPI/bin/Release/*.nupkg --api-key ${{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json

#   deploy-thunderstore:
#     if: ${{ github.event.release.prerelease == false }}
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Download Thunderstore Artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: thunderstore-build
#           path: ./ModMenuAPI/Thunderstore/Packages/

#       - name: Restore Tools
#         run: |
#           dotnet tool restore

#       - name: Publishing to Thunderstore
#         env:
#           TCLI_AUTH_TOKEN: ${{ secrets.THUNDERSTORE_API_TOKEN }}
#         run: |
#           dotnet tcli publish --config-path ./ModMenuAPI/Thunderstore/thunderstore.toml --file ./ModMenuAPI/Thunderstore/Packages/*.zip